import { StyleSpecification } from "@maplibre/maplibre-gl-style-spec";

export const mapStyle: StyleSpecification = {
  version: 8,
  glyphs: "https://demotiles.maplibre.org/font/{fontstack}/{range}.pbf",
  sources: {
    osm: {
      type: "raster",
      tiles: ["https://a.tile.openstreetmap.org/{z}/{x}/{y}.png"],
      tileSize: 256,
      attribution: "&copy; OpenStreetMap Contributors",
      maxzoom: 19,
    },
    vehicles: {
      type: "geojson",
      data: { type: "FeatureCollection", features: [] },
      cluster: false,
      clusterMaxZoom: 14,
      clusterRadius: 5,
    },
    vehicleTraces: {
      type: "geojson",
      data: { type: "FeatureCollection", features: [] },
    },
  },

  layers: [
    {
      id: "osm",
      type: "raster",
      source: "osm",
      paint: {
        "raster-saturation": 0.3,
        "raster-contrast": 0.1,
      },
    },
    {
      id: "vehicle-trace-layer",
      type: "line",
      source: "vehicleTraces",
      layout: {
        "line-cap": "round",
        "line-join": "miter",
        visibility: "none",
      },
      paint: {
        "line-color": "#9353a1",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          6,
          3,
          12,
          7,
          17,
          20,
        ],
        "line-opacity": 0.6,
        "line-blur": 0.5,
      },
    },
    {
      id: "vehicle-layer",
      type: "symbol",
      source: "vehicles",
      layout: {
        "icon-image": [
          "match",
          ["get", "mode"],
          "BUS",
          "bus-icon",
          "FERRY",
          "ferry-icon",
          "RAIL",
          "train-icon",
          "TRAM",
          "tram-icon",
          "bus-red",
        ],
        "icon-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          4,
          0.08,
          8,
          0.12,
          12,
          0.2,
          14,
          0.25,
          18,
          0.35,
        ],
        "icon-allow-overlap": true,
        "text-field": ["get", "lineCode"],
        "text-size": 14,
        "text-font": ["Open Sans Regular", "Arial Unicode MS Regular"],
        "text-anchor": "top-left",
        "text-offset": [0, -2.8],
        "text-allow-overlap": true,
      },
      paint: {
        "text-color": "#000",
        "text-halo-color": "#FFF",
        "text-halo-width": 6,
        "text-opacity": ["interpolate", ["linear"], ["zoom"], 13, 0, 13.01, 1],
      },
    },
    {
      id: "vehicle-follow-layer",
      type: "symbol",
      source: "vehicles",
      layout: {
        "icon-image": "green-marker-icon",
        "icon-size": 0.25,
        "icon-anchor": "bottom",
        "icon-offset": [
          "interpolate",
          ["linear"],
          ["zoom"],
          4,
          ["literal", [0, -30]], // At zoom 4, offset is [0, -30]
          18,
          ["literal", [0, -180]], // At zoom 18, offset is [0, -80]
        ],
        "icon-allow-overlap": true,
      },
      filter: ["==", ["get", "followed"], true],
    },
    {
      id: "delay",
      type: "circle",
      source: "vehicles",
      minzoom: 13,
      paint: {
        "circle-radius": [
          "interpolate",
          ["linear"],
          ["zoom"],
          13,
          9,
          15,
          8,
          17,
          7,
        ],
        "circle-translate": [-20, -30],
        "circle-color": [
          "step",
          ["get", "delay"],
          "#00FF00",
          180,
          "#FFFF00",
          300,
          "#FF0000",
        ],
        "circle-stroke-color": "#000",
        "circle-stroke-width": 2,
      },
    },
    {
      id: "vehicle-delay-heatmap",
      type: "heatmap",
      source: "vehicles",
      maxzoom: 19,
      paint: {
        "heatmap-weight": [
          "interpolate",
          ["linear"],
          ["get", "delay"],
          0,
          0,
          180,
          0.5,
          300,
          1,
        ],
        "heatmap-intensity": ["interpolate", ["linear"], ["zoom"], 0, 1, 14, 3],
        "heatmap-color": [
          "interpolate",
          ["linear"],
          ["heatmap-density"],
          0,
          "rgba(33,102,172,0)",
          0.2,
          "rgb(103,169,207)",
          0.4,
          "rgb(209,229,240)",
          0.6,
          "rgb(253,219,199)",
          0.8,
          "rgb(239,138,98)",
          1,
          "rgb(178,24,43)",
        ],
        "heatmap-radius": ["interpolate", ["linear"], ["zoom"], 0, 2, 14, 20],
        "heatmap-opacity": ["interpolate", ["linear"], ["zoom"], 8, 1, 14, 0.3],
      },
      layout: {
        visibility: "none",
      },
    },
  ],
};
