name: Build
"on":
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - run: npm ci
      - run: npm run check
      - run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: |
            dist
