name: Build PR
"on": pull_request
jobs:
  build:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.user.login != 'dependabot[bot]' }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - run: npm ci
      - run: npm run check
      - run: npm run build
      - name: Copy config
        run: cp .github/environments/config-dev.json dist/bootstrap.json
      - name: Archive build artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist

  preview:
    needs: [build]
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.user.login != 'dependabot[bot]' }}"
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: entur/gha-firebase/.github/workflows/firebase-hosting-preview.yml@v1
    with:
      gcp_project_id: vehicle-map-demo-dev
      environment: dev
      build_artifact_name: dist
      build_artifact_path: dist
