name: Deploy

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: dist
          path: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy config
        run: cp .github/environments/config-dev.json dist/bootstrap.json
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VEHICLE_MAP_DEMO_DEV }}"
          channelId: live
          projectId: vehicle-map-demo-dev
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: dist
          path: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy config
        run: cp .github/environments/config-staging.json dist/bootstrap.json
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VEHICLE_MAP_DEMO_STAGING }}"
          channelId: live
          projectId: vehicle-map-demo-staging
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: dist
          path: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy config
        run: cp .github/environments/config-prod.json dist/bootstrap.json
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VEHICLE_MAP_DEMO_PROD }}"
          channelId: live
          projectId: vehicle-map-demo-prod
